# Generated by Django 4.1 on 2022-08-05 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='guest_schedule',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='level',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('number', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='script',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('head', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='organizers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('patronymic', models.CharField(max_length=20)),
                ('tg_tag', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=12)),
                ('department', models.TextField()),
                ('texts', models.TextField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tg_backend.level')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tg_backend.room')),
            ],
        ),
        migrations.CreateModel(
            name='organizer_schedule',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('finish_time', models.TimeField()),
                ('changer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tg_tag2', to='tg_backend.organizers', to_field='tg_tag')),
                ('tg_tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tg_tag1', to='tg_backend.organizers', to_field='tg_tag')),
            ],
        ),
        migrations.CreateModel(
            name='issue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('desc', models.TextField()),
                ('status', models.CharField(max_length=256)),
                ('tg_tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tg_backend.organizers', to_field='tg_tag')),
            ],
        ),
        migrations.CreateModel(
            name='guest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('patronymic', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=12)),
                ('tg_tag', models.CharField(max_length=20, unique=True)),
                ('vk_link', models.CharField(max_length=20)),
                ('texts', models.TextField()),
                ('team', models.IntegerField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tg_backend.level')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tg_backend.room')),
            ],
        ),
        migrations.CreateModel(
            name='button',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('title_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_backend.script')),
            ],
        ),
        migrations.CreateModel(
            name='broadcast',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tg_backend.level')),
            ],
        ),
    ]
