# Generated by Django 3.2.6 on 2022-09-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
