# Generated by Django 3.2.6 on 2022-09-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_organizer_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('N', 'Not solved'), ('P', 'In progress'), ('F', 'Fixed')], default='N', max_length=256),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='vk_link',
            field=models.CharField(max_length=256),
        ),
    ]
