# Generated by Django 4.1.1 on 2022-09-12 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_useractionlog_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title_from', models.CharField(max_length=256)),
                ('title_to', models.CharField(max_length=256)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=255, verbose_name='Наименование параметра')),
                ('param_val', models.TextField(blank=True, null=True, verbose_name='Значение параметра')),
            ],
            options={
                'verbose_name': 'Параметр бота',
                'verbose_name_plural': 'Параметры бота',
                'ordering': ['param_name'],
            },
        ),
        migrations.CreateModel(
            name='GuestSchedule',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tg_tag', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('status', models.CharField(choices=[('N', 'Not solved'), ('P', 'In progress'), ('F', 'Fixed')], max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Organizers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('patronymic', models.CharField(max_length=20)),
                ('tg_tag', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=12)),
                ('department', models.TextField()),
                ('texts', models.TextField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tgbot.level')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('number', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('head', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.CreateModel(
            name='OrganizerSchedule',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('finish_time', models.TimeField()),
                ('changer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tg_tag2', to='tgbot.organizers', to_field='tg_tag')),
                ('tg_tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tg_tag1', to='tgbot.organizers', to_field='tg_tag')),
            ],
        ),
        migrations.AddField(
            model_name='organizers',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tgbot.room'),
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('patronymic', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=12)),
                ('tg_tag', models.CharField(max_length=20, unique=True)),
                ('vk_link', models.CharField(max_length=20)),
                ('texts', models.TextField()),
                ('team', models.IntegerField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tgbot.level')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tgbot.room')),
            ],
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tgbot.level')),
            ],
        ),
    ]
