FIRST_DAY = "1.10.2022"
SECOND_DAY = "2.10.2022"

BTN_1 = 'BTN_1'
BTN_2 = 'BTN_2'
BTN_3 = 'BTN_3'

BUTTON_BACK_IN_PLACE = 'IN_PLACE_BACK'

SECRET_LEVEL_BUTTON = 'SCRT_LVL'
CONFIRM_DECLINE_BROADCAST = 'CNFM_DCLN_BRDCST'
CONFIRM_BROADCAST = 'CONFIRM'
DECLINE_BROADCAST = 'DECLINE'
ISSUE_MESSAGE_WAITING = 0

SET_NOT_FIXED = 'N'
SET_IN_PROGRESS = 'P'
SET_FIXED = "F"
SET_ONE_OR_ALL_ISS = "SET_ONE_OR_ALL"
SET_ALL_ISS = "SET_ALL"

GET_ALL_ISS = "USER_ALL"

CONFIRM_DELETING = "CNFRM_DEL"
DECLINE_DELETING = "DCLN_DEL"

#TODO дополнить DEPART_LIST
DEPART_LIST = ['Админка','Пиар','Игротехника','Техотдел'] 